Refactor source tree into directories
Now instead of almost every file in the top level, move the old go code
into its own directory 'golang', and the C++ code into it's own 'src'

Also removes a few obsolete scripts that were used to work on Android
before Android fully switched to Kati.

diff --git a/clang-format-check b/clang-format-check
--- a/clang-format-check
+++ b/clang-format-check
@@ -4,11 +4,11 @@ if [ -z "$CLANG_FORMAT" ]; then
   CLANG_FORMAT="clang-format"
 fi
 
-for f in $(ls *.cc *.h); do
+for f in $(ls src/*.cc src/*.h); do
   if ! diff -U 1 <($CLANG_FORMAT $f) $f; then
     echo
     echo "!!!!!!"
-    echo "!! Failed clang-format check, please run 'clang-format -i *.cc *.h'" 1>&2
+    echo "!! Failed clang-format check, please run 'clang-format -i src/*.cc src/*.h'" 1>&2
     echo "!!!!!!"
     exit 1
   fi
